[[main]]
  name = "SIer脱出"
  url = "/categories/sier脱出/"
  weight = 10

[[main]]
  name = "PMOキャリア"
  url = "/categories/pmoキャリア/"
  weight = 20

[[main]]
  name = "コンサル転職"
  url = "/categories/コンサル転職/"
  weight = 30

[[main]]
  name = "フリーランス"
  url = "/categories/フリーランス/"
  weight = 40

[[main]]
  name = "学び・資格"
  url = "/categories/学び資格/"
  weight = 50

[[main]]
  name = "プロフィール"
  url = "/about/"
  weight = 60

[[main]]
  name = "お問い合わせ"
  url = "/contact/"
  weight = 90

[[footer]]
  name = "プライバシーポリシー"
  url = "/privacy-policy/"
  weight = 10

[[footer]]
  name = "免責事項"
  url = "/disclaimer/"
  weight = 20

[[footer]]
  name = "お問い合わせ"
  url = "/contact/"
  weight = 30
